#!/usr/bin/env python3
"""Extract the real Unicode planetary outlines and emit deterministic SVG paths.

No symbol is hand drawn. By default the script downloads two exact Noto font
files from one immutable upstream commit, caches them outside Git, and traces
their contours with FontTools' SVGPathPen.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import urllib.request
from pathlib import Path
from typing import Any

try:
    from fontTools.pens.boundsPen import BoundsPen
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.ttLib import TTFont
except ImportError as error:
    raise SystemExit(
        "FontTools is required. Install it with: "
        "python3 -m pip install -r scripts/planet-glyph-requirements.txt"
    ) from error

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "planet.ts"
OUTPUT = ROOT / "src" / "planet-glyph-paths.ts"
CACHE = ROOT / ".cache" / "planet-glyph-fonts"
NOTO_COMMIT = "ffebf8c1ee449e544955a7e813c54f9b73848eac"
RAW = f"https://raw.githubusercontent.com/notofonts/noto-fonts/{NOTO_COMMIT}/hinted/ttf"
PINNED_FONTS = {
    "Noto Sans Symbols": (
        f"{RAW}/NotoSansSymbols/NotoSansSymbols-Regular.ttf",
        CACHE / "NotoSansSymbols-Regular.ttf",
    ),
    "Noto Sans Symbols 2": (
        f"{RAW}/NotoSansSymbols2/NotoSansSymbols2-Regular.ttf",
        CACHE / "NotoSansSymbols2-Regular.ttf",
    ),
}

PLANET_PATTERN = re.compile(
    r'\{\s*key:\s*"(?P<key>[^"]+)",\s*glyph:\s*"(?P<glyph>[^"]+)",'
)
SUN_PATTERN = re.compile(r'calibrationSunGlyph\s*=\s*"(?P<glyph>[^"]+)"')


def download(url: str, destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.is_file() and destination.stat().st_size > 0:
        return destination

    temporary = destination.with_suffix(destination.suffix + ".part")
    with urllib.request.urlopen(url, timeout=60) as response:
        temporary.write_bytes(response.read())
    temporary.replace(destination)
    return destination


def trace(
    font: TTFont,
    font_file: Path,
    family: str,
    unicode_glyph: str,
) -> dict[str, Any] | None:
    cmap = font.getBestCmap() or {}
    glyph_name = cmap.get(ord(unicode_glyph))
    if glyph_name is None:
        return None

    glyph_set = font.getGlyphSet()
    glyph = glyph_set[glyph_name]
    path_pen = SVGPathPen(glyph_set)
    bounds_pen = BoundsPen(glyph_set)
    glyph.draw(path_pen)
    glyph.draw(bounds_pen)
    if bounds_pen.bounds is None:
        raise SystemExit(f"Glyph {unicode_glyph!r} has no vector outline")

    min_x, min_y, max_x, max_y = bounds_pen.bounds
    path = path_pen.getCommands()
    if not path:
        raise SystemExit(f"Glyph {unicode_glyph!r} produced an empty SVG path")

    return {
        "unicode": unicode_glyph,
        "path": path,
        "minX": min_x,
        "minY": min_y,
        "maxX": max_x,
        "maxY": max_y,
        "font": family,
        "fontCommit": NOTO_COMMIT,
        "fontSha256": hashlib.sha256(font_file.read_bytes()).hexdigest(),
    }


def emit(planets: dict[str, dict[str, Any]], sun: dict[str, Any]) -> str:
    lines = [
        "/* Generated by scripts/generate-planet-glyphs.py. Do not edit by hand. */",
        "export interface TracedGlyph {",
        "  readonly unicode: string;",
        "  readonly path: string;",
        "  readonly minX: number;",
        "  readonly minY: number;",
        "  readonly maxX: number;",
        "  readonly maxY: number;",
        "  readonly font: string;",
        "  readonly fontCommit: string;",
        "  readonly fontSha256: string;",
        "}",
        "",
        "export const tracedPlanetGlyphs = {",
    ]
    for key, value in planets.items():
        encoded = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        lines.append(f"  {key}: {encoded},")
    lines.extend(
        [
            "} as const satisfies Record<string, TracedGlyph>;",
            "",
            "export const tracedCalibrationSun = "
            + json.dumps(sun, ensure_ascii=False, separators=(",", ":"))
            + " as const satisfies TracedGlyph;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--symbols", type=Path)
    parser.add_argument("--symbols2", type=Path)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed generated module is not current",
    )
    arguments = parser.parse_args()

    explicit = {
        "Noto Sans Symbols": arguments.symbols,
        "Noto Sans Symbols 2": arguments.symbols2,
    }
    fonts: list[tuple[str, Path, TTFont]] = []
    for family, (url, cached) in PINNED_FONTS.items():
        path = explicit[family] or download(url, cached)
        if not path.is_file():
            raise SystemExit(f"Font file does not exist: {path}")
        fonts.append((family, path, TTFont(path)))

    source = SOURCE.read_text(encoding="utf-8")
    planet_sources = PLANET_PATTERN.findall(source)
    sun_match = SUN_PATTERN.search(source)
    if len(planet_sources) != 11 or sun_match is None:
        raise SystemExit(
            "Could not read the eleven planets and calibration Sun from src/planet.ts"
        )

    def extract(unicode_glyph: str) -> dict[str, Any]:
        if len(unicode_glyph) != 1:
            raise SystemExit(f"Expected one Unicode scalar, received {unicode_glyph!r}")
        for family, path, font in fonts:
            result = trace(font, path, family, unicode_glyph)
            if result is not None:
                return result
        raise SystemExit(f"No pinned font contains {unicode_glyph!r}")

    planets = {key: extract(glyph) for key, glyph in planet_sources}
    sun = extract(sun_match.group("glyph"))
    output = emit(planets, sun)

    if arguments.check:
        current = arguments.output.read_text(encoding="utf-8") \
            if arguments.output.is_file() else ""
        if current != output:
            raise SystemExit(
                "src/planet-glyph-paths.ts is stale; run: "
                "python3 scripts/generate-planet-glyphs.py"
            )
        print("Planet glyph SVG paths match the pinned Unicode font outlines")
        return

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(output, encoding="utf-8")
    print(
        f"Generated {arguments.output.relative_to(ROOT)} from pinned Unicode font outlines"
    )


if __name__ == "__main__":
    main()
