#!/usr/bin/env python3
"""Extract Unicode planetary glyph outlines and emit deterministic SVG paths.

This script does not redraw or approximate symbols. It reads the actual outline
from Noto Sans Symbols / Noto Sans Symbols 2 with FontTools' SVGPathPen.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path
from typing import Any

try:
    from fontTools.pens.boundsPen import BoundsPen
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.ttLib import TTFont
except ImportError as error:
    raise SystemExit(
        "FontTools is required. Install it with: python3 -m pip install fonttools==4.63.0"
    ) from error

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "planet.ts"
OUTPUT = ROOT / "src" / "planet-glyph-paths.ts"

PLANET_PATTERN = re.compile(
    r'\{\s*key:\s*"(?P<key>[^"]+)",\s*glyph:\s*"(?P<glyph>[^"]+)",'
)
SUN_PATTERN = re.compile(r'calibrationSunGlyph\s*=\s*"(?P<glyph>[^"]+)"')


def font_path(family: str) -> Path:
    result = subprocess.run(
        ["fc-match", "-f", "%{file}", family],
        check=True,
        capture_output=True,
        text=True,
    )
    path = Path(result.stdout.strip())
    if not path.is_file():
        raise SystemExit(f"Could not resolve a font file for {family}")
    return path


def trace(font: TTFont, font_file: Path, family: str, unicode_glyph: str) -> dict[str, Any] | None:
    cmap = font.getBestCmap() or {}
    glyph_name = cmap.get(ord(unicode_glyph))
    if glyph_name is None:
        return None

    glyph_set = font.getGlyphSet()
    glyph = glyph_set[glyph_name]
    path_pen = SVGPathPen(glyph_set)
    glyph.draw(path_pen)
    bounds_pen = BoundsPen(glyph_set)
    glyph.draw(bounds_pen)
    if bounds_pen.bounds is None:
        raise SystemExit(f"Glyph {unicode_glyph!r} has no vector outline")

    min_x, min_y, max_x, max_y = bounds_pen.bounds
    path = path_pen.getCommands()
    if not path:
        raise SystemExit(f"Glyph {unicode_glyph!r} produced an empty SVG path")

    return {
        "unicode": unicode_glyph,
        "path": path,
        "minX": min_x,
        "minY": min_y,
        "maxX": max_x,
        "maxY": max_y,
        "font": family,
        "fontSha256": hashlib.sha256(font_file.read_bytes()).hexdigest(),
    }


def emit(planets: dict[str, dict[str, Any]], sun: dict[str, Any]) -> str:
    lines = [
        "/* Generated by scripts/generate-planet-glyphs.py. Do not edit by hand. */",
        "export interface TracedGlyph {",
        "  readonly unicode: string;",
        "  readonly path: string;",
        "  readonly minX: number;",
        "  readonly minY: number;",
        "  readonly maxX: number;",
        "  readonly maxY: number;",
        "  readonly font: string;",
        "  readonly fontSha256: string;",
        "}",
        "",
        "export const tracedPlanetGlyphs = {",
    ]
    for key, value in planets.items():
        encoded = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        lines.append(f"  {key}: {encoded},")
    lines.extend(
        [
            "} as const satisfies Record<string, TracedGlyph>;",
            "",
            "export const tracedCalibrationSun = "
            + json.dumps(sun, ensure_ascii=False, separators=(",", ":"))
            + " as const satisfies TracedGlyph;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--symbols", type=Path)
    parser.add_argument("--symbols2", type=Path)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    arguments = parser.parse_args()

    symbols_file = arguments.symbols or font_path("Noto Sans Symbols")
    symbols2_file = arguments.symbols2 or font_path("Noto Sans Symbols 2")
    fonts = [
        ("Noto Sans Symbols", symbols_file, TTFont(symbols_file)),
        ("Noto Sans Symbols 2", symbols2_file, TTFont(symbols2_file)),
    ]

    source = SOURCE.read_text(encoding="utf-8")
    planet_sources = PLANET_PATTERN.findall(source)
    sun_match = SUN_PATTERN.search(source)
    if len(planet_sources) != 11 or sun_match is None:
        raise SystemExit("Could not read the eleven planets and calibration Sun from src/planet.ts")

    def extract(unicode_glyph: str) -> dict[str, Any]:
        if len(unicode_glyph) != 1:
            raise SystemExit(f"Expected one Unicode scalar, received {unicode_glyph!r}")
        for family, path, font in fonts:
            result = trace(font, path, family, unicode_glyph)
            if result is not None:
                return result
        raise SystemExit(f"No configured font contains {unicode_glyph!r}")

    planets = {key: extract(glyph) for key, glyph in planet_sources}
    sun = extract(sun_match.group("glyph"))
    output = emit(planets, sun)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(output, encoding="utf-8")
    print(f"Generated {arguments.output.relative_to(ROOT)} from Unicode font outlines")


if __name__ == "__main__":
    main()
